import { createContext, useContext, useState, useEffect } from 'react'

const translations = {
  english: {
    // Nav / Layout
    'Overview': 'Overview', 'Case Management': 'Case Management', 'Hearings': 'Hearings',
    'Legal Process': 'Legal Process', 'Admin & Reports': 'Admin & Reports',
    'Dashboard': 'Dashboard', 'Cases': 'Cases', 'File Case': 'File Case',
    'Pending Docs': 'Pending Docs', 'Schedule': 'Schedule', 'Judge Slots': 'Judge Slots',
    'Appeals': 'Appeals', 'File Appeal': 'File Appeal', 'Workflow / SLA': 'Workflow / SLA',
    'Run Compliance Check': 'Run Compliance Check', 'Compliance Records': 'Compliance Records',
    'Audits': 'Audits', 'Reports': 'Reports', 'Users': 'Users', 'Audit Logs': 'Audit Logs',
    'Notifications': 'Notifications', 'Navigation': 'Navigation', 'More': 'More',
    'Settings': 'Settings', 'Theme': 'Theme', 'Language': 'Language',
    'Dark': 'Dark', 'Light': 'Light', 'Change Password': 'Change Password', 'Sign Out': 'Sign Out',
    // Dashboard
    'Good morning': 'Good morning', 'Good afternoon': 'Good afternoon', 'Good evening': 'Good evening',
    "Here's what's happening with your cases today.": "Here's what's happening with your cases today.",
    'Total Cases': 'Total Cases', 'SLA Breached': 'SLA Breached',
    'File New Case': 'File New Case', 'Schedule Hearing': 'Schedule Hearing',
    'Recent Cases': 'Recent Cases', 'View all →': 'View all →',
    'No cases yet.': 'No cases yet.', 'File your first case': 'File your first case',
    'No cases available yet.': 'No cases available yet.',
    'ID': 'ID', 'TITLE': 'TITLE', 'STATUS': 'STATUS', 'FILED': 'FILED', 'View': 'View',
    // Cases
    'Cases': 'Cases', '+ File New Case': '+ File New Case', 'Filter by status:': 'Filter by status:',
    'All': 'All', 'Refresh': 'Refresh', 'No cases found': 'No cases found', 'Loading...': 'Loading...',
    'Title': 'Title', 'Litigant': 'Litigant', 'Lawyer': 'Lawyer', 'Filed': 'Filed', 'Open': 'Open',
    // File Case
    'File New Case': 'File New Case', 'Case Title': 'Case Title',
    'Litigant ID (user email or id)': 'Litigant ID (user email or id)',
    'Lawyer ID (optional)': 'Lawyer ID (optional)', 'Filing...': 'Filing...', 'File Case': 'File Case',
    // Hearings
    '+ Schedule Hearing': '+ Schedule Hearing', 'Filter:': 'Filter:',
    'No hearings': 'No hearings', 'Case': 'Case', 'Judge': 'Judge', 'Date': 'Date', 'Time': 'Time',
    // Schedule Hearing
    'Schedule Hearing': 'Schedule Hearing', 'Add a slot for the judge first, then use its ID here.': 'Add a slot for the judge first, then use its ID here.',
    'Case ID': 'Case ID', 'Judge ID': 'Judge ID', 'Hearing Date': 'Hearing Date',
    'Hearing Time': 'Hearing Time', 'Schedule Slot ID': 'Schedule Slot ID',
    'Scheduled By (user id)': 'Scheduled By (user id)', 'Scheduling...': 'Scheduling...', 'Schedule': 'Schedule',
    // Appeals
    'No appeals found': 'No appeals found',
    // Reports
    'Generate Report': 'Generate Report', 'Generating...': 'Generating...',
    // Common
    'Back': 'Back', 'Save': 'Save', 'Cancel': 'Cancel', 'Submit': 'Submit',
    'Error': 'Error', 'Success': 'Success', 'Close': 'Close',
    'Name': 'Name', 'Email': 'Email', 'Role': 'Role', 'Action': 'Action',
    'Create Account': 'Create Account', 'Welcome back': 'Welcome back',
    'Sign in to your CaseFlow account': 'Sign in to your CaseFlow account',
    'Email address': 'Email address', 'Password': 'Password', 'Remember me': 'Remember me',
    'Forgot password?': 'Forgot password?', 'Sign In': 'Sign In',
    "Don't have an account?": "Don't have an account?", 'Create one': 'Create one',
    '← Back to home': '← Back to home',
    'Already have an account?': 'Already have an account?', 'Sign in': 'Sign in',
    'Register as a Litigant on CaseFlow': 'Register as a Litigant on CaseFlow',
    'Full Name': 'Full Name', 'Phone (10 digits)': 'Phone (10 digits)',
    'Password (min 6 characters)': 'Password (min 6 characters)',
    'Create a secure password': 'Create a secure password', 'Creating...': 'Creating...',
  },

  hindi: {
    'Overview': 'अवलोकन', 'Case Management': 'केस प्रबंधन', 'Hearings': 'सुनवाई',
    'Legal Process': 'कानूनी प्रक्रिया', 'Admin & Reports': 'एडमिन और रिपोर्ट',
    'Dashboard': 'डैशबोर्ड', 'Cases': 'केस', 'File Case': 'केस दर्ज करें',
    'Pending Docs': 'लंबित दस्तावेज', 'Schedule': 'शेड्यूल', 'Judge Slots': 'जज स्लॉट्स',
    'Appeals': 'अपील', 'File Appeal': 'अपील दर्ज करें', 'Workflow / SLA': 'वर्कफ़्लो / SLA',
    'Run Compliance Check': 'अनुपालन जाँच चलाएँ', 'Compliance Records': 'अनुपालन रिकॉर्ड',
    'Audits': 'ऑडिट', 'Reports': 'रिपोर्ट्स', 'Users': 'उपयोगकर्ता',
    'Audit Logs': 'ऑडिट लॉग्स', 'Notifications': 'सूचनाएँ', 'Navigation': 'नेविगेशन',
    'More': 'और', 'Settings': 'सेटिंग्स', 'Theme': 'थीम', 'Language': 'भाषा',
    'Dark': 'डार्क', 'Light': 'लाइट', 'Change Password': 'पासवर्ड बदलें', 'Sign Out': 'साइन आउट',
    'Good morning': 'सुप्रभात', 'Good afternoon': 'शुभ दोपहर', 'Good evening': 'शुभ संध्या',
    "Here's what's happening with your cases today.": 'आज आपके केस में यह हो रहा है।',
    'Total Cases': 'कुल केस', 'SLA Breached': 'SLA उल्लंघन',
    'File New Case': 'नया केस दर्ज करें', 'Schedule Hearing': 'सुनवाई शेड्यूल करें',
    'Recent Cases': 'हालिया केस', 'View all →': 'सभी देखें →',
    'No cases yet.': 'अभी कोई केस नहीं।', 'File your first case': 'अपना पहला केस दर्ज करें',
    'No cases available yet.': 'अभी कोई केस उपलब्ध नहीं।',
    'ID': 'आईडी', 'TITLE': 'शीर्षक', 'STATUS': 'स्थिति', 'FILED': 'दर्ज तिथि', 'View': 'देखें',
    '+ File New Case': '+ नया केस दर्ज करें', 'Filter by status:': 'स्थिति से फ़िल्टर करें:',
    'All': 'सभी', 'Refresh': 'रिफ्रेश', 'No cases found': 'कोई केस नहीं मिला', 'Loading...': 'लोड हो रहा है...',
    'Title': 'शीर्षक', 'Litigant': 'वादी', 'Lawyer': 'वकील', 'Filed': 'दर्ज', 'Open': 'खोलें',
    'File New Case': 'नया केस दर्ज करें', 'Case Title': 'केस शीर्षक',
    'Litigant ID (user email or id)': 'वादी ID (ईमेल या ID)', 'Lawyer ID (optional)': 'वकील ID (वैकल्पिक)',
    'Filing...': 'दर्ज हो रहा है...', 'File Case': 'केस दर्ज करें',
    '+ Schedule Hearing': '+ सुनवाई शेड्यूल करें', 'Filter:': 'फ़िल्टर:',
    'No hearings': 'कोई सुनवाई नहीं', 'Case': 'केस', 'Judge': 'न्यायाधीश', 'Date': 'तारीख', 'Time': 'समय',
    'Schedule Hearing': 'सुनवाई शेड्यूल करें',
    'Add a slot for the judge first, then use its ID here.': 'पहले जज के लिए स्लॉट जोड़ें, फिर उसकी ID यहाँ डालें।',
    'Case ID': 'केस ID', 'Judge ID': 'जज ID', 'Hearing Date': 'सुनवाई तिथि',
    'Hearing Time': 'सुनवाई समय', 'Schedule Slot ID': 'स्लॉट ID',
    'Scheduled By (user id)': 'शेड्यूल करने वाला (यूजर ID)', 'Scheduling...': 'शेड्यूल हो रहा है...',
    'Generate Report': 'रिपोर्ट बनाएं', 'Generating...': 'बन रहा है...',
    'Back': 'वापस', 'Save': 'सहेजें', 'Cancel': 'रद्द करें', 'Submit': 'जमा करें',
    'Name': 'नाम', 'Email': 'ईमेल', 'Role': 'भूमिका', 'Action': 'कार्रवाई',
    'Welcome back': 'वापस स्वागत है', 'Sign in to your CaseFlow account': 'अपने CaseFlow खाते में साइन इन करें',
    'Email address': 'ईमेल पता', 'Password': 'पासवर्ड', 'Remember me': 'मुझे याद रखें',
    'Forgot password?': 'पासवर्ड भूल गए?', 'Sign In': 'साइन इन',
    "Don't have an account?": 'खाता नहीं है?', 'Create one': 'बनाएं',
    '← Back to home': '← होम पर वापस', 'Already have an account?': 'पहले से खाता है?', 'Sign in': 'साइन इन',
    'Register as a Litigant on CaseFlow': 'CaseFlow पर वादी के रूप में पंजीकृत हों',
    'Full Name': 'पूरा नाम', 'Phone (10 digits)': 'फ़ोन (10 अंक)',
    'Password (min 6 characters)': 'पासवर्ड (कम से कम 6 अक्षर)',
    'Create a secure password': 'एक सुरक्षित पासवर्ड बनाएं', 'Creating...': 'बन रहा है...',
    'Create Account': 'खाता बनाएं', 'No appeals found': 'कोई अपील नहीं मिली',
  },

  bengali: {
    'Overview': 'ওভারভিউ', 'Case Management': 'মামলা ব্যবস্থাপনা', 'Hearings': 'শুনানি',
    'Legal Process': 'আইনি প্রক্রিয়া', 'Admin & Reports': 'অ্যাডমিন ও রিপোর্ট',
    'Dashboard': 'ড্যাশবোর্ড', 'Cases': 'মামলা', 'File Case': 'মামলা দায়ের',
    'Pending Docs': 'অপেক্ষমাণ নথি', 'Schedule': 'সময়সূচি', 'Judge Slots': 'বিচারক স্লট',
    'Appeals': 'আপিল', 'File Appeal': 'আপিল দায়ের', 'Workflow / SLA': 'ওয়ার্কফ্লো / SLA',
    'Run Compliance Check': 'কমপ্লায়েন্স চেক চালান', 'Compliance Records': 'কমপ্লায়েন্স রেকর্ড',
    'Audits': 'অডিট', 'Reports': 'রিপোর্ট', 'Users': 'ব্যবহারকারী',
    'Audit Logs': 'অডিট লগ', 'Notifications': 'নোটিফিকেশন', 'Navigation': 'নেভিগেশন',
    'More': 'আরও', 'Settings': 'সেটিংস', 'Theme': 'থিম', 'Language': 'ভাষা',
    'Dark': 'ডার্ক', 'Light': 'লাইট', 'Change Password': 'পাসওয়ার্ড পরিবর্তন', 'Sign Out': 'সাইন আউট',
    'Good morning': 'শুভ সকাল', 'Good afternoon': 'শুভ অপরাহ্ন', 'Good evening': 'শুভ সন্ধ্যা',
    "Here's what's happening with your cases today.": 'আজ আপনার মামলায় এটি ঘটছে।',
    'Total Cases': 'মোট মামলা', 'SLA Breached': 'SLA লঙ্ঘিত',
    'File New Case': 'নতুন মামলা দায়ের', 'Schedule Hearing': 'শুনানি নির্ধারণ',
    'Recent Cases': 'সাম্প্রতিক মামলা', 'View all →': 'সব দেখুন →',
    'No cases yet.': 'এখনও কোনো মামলা নেই।', 'File your first case': 'আপনার প্রথম মামলা দায়ের করুন',
    'No cases available yet.': 'এখনও কোনো মামলা নেই।',
    'ID': 'ID', 'TITLE': 'শিরোনাম', 'STATUS': 'অবস্থা', 'FILED': 'দাখিল', 'View': 'দেখুন',
    '+ File New Case': '+ নতুন মামলা দায়ের', 'Filter by status:': 'অবস্থা দিয়ে ফিল্টার:',
    'All': 'সব', 'Refresh': 'রিফ্রেশ', 'No cases found': 'কোনো মামলা পাওয়া যায়নি', 'Loading...': 'লোড হচ্ছে...',
    'Title': 'শিরোনাম', 'Litigant': 'বাদী', 'Lawyer': 'আইনজীবী', 'Filed': 'দাখিল', 'Open': 'খুলুন',
    'Case Title': 'মামলার শিরোনাম', 'Litigant ID (user email or id)': 'বাদী ID',
    'Lawyer ID (optional)': 'আইনজীবী ID (ঐচ্ছিক)', 'Filing...': 'দাখিল হচ্ছে...', 'File Case': 'মামলা দায়ের',
    '+ Schedule Hearing': '+ শুনানি নির্ধারণ', 'Filter:': 'ফিল্টার:', 'No hearings': 'কোনো শুনানি নেই',
    'Case': 'মামলা', 'Judge': 'বিচারক', 'Date': 'তারিখ', 'Time': 'সময়',
    'Case ID': 'মামলা ID', 'Judge ID': 'বিচারক ID', 'Hearing Date': 'শুনানির তারিখ',
    'Hearing Time': 'শুনানির সময়', 'Schedule Slot ID': 'স্লট ID',
    'Scheduled By (user id)': 'নির্ধারণকারী (ইউজার ID)', 'Scheduling...': 'নির্ধারণ হচ্ছে...',
    'Generate Report': 'রিপোর্ট তৈরি করুন', 'Generating...': 'তৈরি হচ্ছে...',
    'Back': 'ফিরুন', 'Save': 'সংরক্ষণ', 'Cancel': 'বাতিল', 'Submit': 'জমা দিন',
    'Name': 'নাম', 'Email': 'ইমেইল', 'Role': 'ভূমিকা', 'Action': 'পদক্ষেপ',
    'Welcome back': 'স্বাগতম', 'Sign in to your CaseFlow account': 'আপনার CaseFlow অ্যাকাউন্টে সাইন ইন করুন',
    'Email address': 'ইমেইল ঠিকানা', 'Password': 'পাসওয়ার্ড', 'Remember me': 'আমাকে মনে রাখুন',
    'Forgot password?': 'পাসওয়ার্ড ভুলে গেছেন?', 'Sign In': 'সাইন ইন',
    "Don't have an account?": 'অ্যাকাউন্ট নেই?', 'Create one': 'তৈরি করুন',
    '← Back to home': '← হোমে ফিরুন', 'Already have an account?': 'অ্যাকাউন্ট আছে?', 'Sign in': 'সাইন ইন',
    'Register as a Litigant on CaseFlow': 'CaseFlow-এ বাদী হিসেবে নিবন্ধন করুন',
    'Full Name': 'পুরো নাম', 'Phone (10 digits)': 'ফোন (10 সংখ্যা)',
    'Password (min 6 characters)': 'পাসওয়ার্ড (ন্যূনতম ৬ অক্ষর)',
    'Create a secure password': 'একটি নিরাপদ পাসওয়ার্ড তৈরি করুন', 'Creating...': 'তৈরি হচ্ছে...',
    'Create Account': 'অ্যাকাউন্ট তৈরি', 'No appeals found': 'কোনো আপিল পাওয়া যায়নি',
  },

  tamil: {
    'Overview': 'மேலோட்டம்', 'Case Management': 'வழக்கு மேலாண்மை', 'Hearings': 'விசாரணைகள்',
    'Legal Process': 'சட்ட செயல்முறை', 'Admin & Reports': 'அட்மின் மற்றும் அறிக்கைகள்',
    'Dashboard': 'டாஷ்போர்டு', 'Cases': 'வழக்குகள்', 'File Case': 'வழக்கு பதிவு',
    'Pending Docs': 'நிலுவை ஆவணங்கள்', 'Schedule': 'அட்டவணை', 'Judge Slots': 'நீதிபதி இடங்கள்',
    'Appeals': 'மேல்முறையீடுகள்', 'File Appeal': 'மேல்முறையீடு பதிவு', 'Workflow / SLA': 'பணிச்சுற்று / SLA',
    'Run Compliance Check': 'இணக்க சோதனை இயக்கவும்', 'Compliance Records': 'இணக்க பதிவுகள்',
    'Audits': 'தணிக்கைகள்', 'Reports': 'அறிக்கைகள்', 'Users': 'பயனர்கள்',
    'Audit Logs': 'தணிக்கை பதிவுகள்', 'Notifications': 'அறிவிப்புகள்', 'Navigation': 'வழிசெலுத்தல்',
    'More': 'மேலும்', 'Settings': 'அமைப்புகள்', 'Theme': 'தீம்', 'Language': 'மொழி',
    'Dark': 'டார்க்', 'Light': 'லைட்', 'Change Password': 'கடவுச்சொல் மாற்று', 'Sign Out': 'வெளியேறு',
    'Good morning': 'காலை வணக்கம்', 'Good afternoon': 'மதிய வணக்கம்', 'Good evening': 'மாலை வணக்கம்',
    "Here's what's happening with your cases today.": 'இன்று உங்கள் வழக்குகளில் இது நடக்கிறது.',
    'Total Cases': 'மொத்த வழக்குகள்', 'SLA Breached': 'SLA மீறல்',
    'File New Case': 'புதிய வழக்கு பதிவு', 'Schedule Hearing': 'விசாரணை திட்டமிடு',
    'Recent Cases': 'சமீபத்திய வழக்குகள்', 'View all →': 'அனைத்தும் காண →',
    'No cases yet.': 'இன்னும் வழக்குகள் இல்லை.', 'File your first case': 'உங்கள் முதல் வழக்கைப் பதிவு செய்யுங்கள்',
    'No cases available yet.': 'இன்னும் வழக்குகள் இல்லை.',
    'ID': 'ID', 'TITLE': 'தலைப்பு', 'STATUS': 'நிலை', 'FILED': 'பதிவு தேதி', 'View': 'பார்க்க',
    '+ File New Case': '+ புதிய வழக்கு', 'Filter by status:': 'நிலை மூலம் வடிகட்டு:',
    'All': 'அனைத்தும்', 'Refresh': 'புதுப்பி', 'No cases found': 'வழக்குகள் இல்லை', 'Loading...': 'ஏற்றுகிறது...',
    'Title': 'தலைப்பு', 'Litigant': 'முறையீட்டாளர்', 'Lawyer': 'வழக்கறிஞர்', 'Filed': 'பதிவு', 'Open': 'திற',
    'Case Title': 'வழக்கு தலைப்பு', 'Litigant ID (user email or id)': 'முறையீட்டாளர் ID',
    'Lawyer ID (optional)': 'வழக்கறிஞர் ID (விருப்பமானது)', 'Filing...': 'பதிவு செய்கிறது...', 'File Case': 'வழக்கு பதிவு',
    '+ Schedule Hearing': '+ விசாரணை', 'Filter:': 'வடிகட்டு:', 'No hearings': 'விசாரணை இல்லை',
    'Case': 'வழக்கு', 'Judge': 'நீதிபதி', 'Date': 'தேதி', 'Time': 'நேரம்',
    'Case ID': 'வழக்கு ID', 'Judge ID': 'நீதிபதி ID', 'Hearing Date': 'விசாரணை தேதி',
    'Hearing Time': 'விசாரணை நேரம்', 'Schedule Slot ID': 'ஸ்லாட் ID',
    'Scheduled By (user id)': 'திட்டமிட்டவர் (பயனர் ID)', 'Scheduling...': 'திட்டமிடுகிறது...',
    'Generate Report': 'அறிக்கை உருவாக்கு', 'Generating...': 'உருவாக்குகிறது...',
    'Back': 'திரும்பு', 'Save': 'சேமி', 'Cancel': 'ரத்து', 'Submit': 'சமர்ப்பி',
    'Name': 'பெயர்', 'Email': 'மின்னஞ்சல்', 'Role': 'பங்கு', 'Action': 'நடவடிக்கை',
    'Welcome back': 'மீண்டும் வரவேற்கிறோம்', 'Sign in to your CaseFlow account': 'உங்கள் CaseFlow கணக்கில் உள்நுழைக',
    'Email address': 'மின்னஞ்சல் முகவரி', 'Password': 'கடவுச்சொல்', 'Remember me': 'என்னை நினைவில் வை',
    'Forgot password?': 'கடவுச்சொல் மறந்தீர்களா?', 'Sign In': 'உள்நுழை',
    "Don't have an account?": 'கணக்கு இல்லையா?', 'Create one': 'உருவாக்குங்கள்',
    '← Back to home': '← முகப்புக்கு திரும்பு', 'Already have an account?': 'ஏற்கனவே கணக்கு உள்ளதா?', 'Sign in': 'உள்நுழை',
    'Register as a Litigant on CaseFlow': 'CaseFlow-ல் வழக்காளராக பதிவு செய்யுங்கள்',
    'Full Name': 'முழு பெயர்', 'Phone (10 digits)': 'தொலைபேசி (10 இலக்கம்)',
    'Password (min 6 characters)': 'கடவுச்சொல் (குறைந்தது 6 எழுத்துக்கள்)',
    'Create a secure password': 'பாதுகாப்பான கடவுச்சொல் உருவாக்கு', 'Creating...': 'உருவாக்குகிறது...',
    'Create Account': 'கணக்கு உருவாக்கு', 'No appeals found': 'மேல்முறையீடுகள் இல்லை',
  },

  telugu: {
    'Overview': 'సారాంశం', 'Case Management': 'కేసు నిర్వహణ', 'Hearings': 'విచారణలు',
    'Legal Process': 'న్యాయ ప్రక్రియ', 'Admin & Reports': 'అడ్మిన్ & రిపోర్ట్స్',
    'Dashboard': 'డాష్‌బోర్డ్', 'Cases': 'కేసులు', 'File Case': 'కేసు నమోదు',
    'Pending Docs': 'పెండింగ్ పత్రాలు', 'Schedule': 'షెడ్యూల్', 'Judge Slots': 'న్యాయమూర్తి స్లాట్లు',
    'Appeals': 'అపీల్స్', 'File Appeal': 'అపీలు నమోదు', 'Workflow / SLA': 'వర్క్‌ఫ్లో / SLA',
    'Run Compliance Check': 'కాంప్లయన్స్ చెక్ నడపండి', 'Compliance Records': 'కాంప్లయన్స్ రికార్డులు',
    'Audits': 'ఆడిట్లు', 'Reports': 'రిపోర్టులు', 'Users': 'వినియోగదారులు',
    'Audit Logs': 'ఆడిట్ లాగ్లు', 'Notifications': 'నోటిఫికేషన్లు', 'Navigation': 'నావిగేషన్',
    'More': 'మరిన్ని', 'Settings': 'సెట్టింగ్స్', 'Theme': 'థీమ్', 'Language': 'భాష',
    'Dark': 'డార్క్', 'Light': 'లైట్', 'Change Password': 'పాస్‌వర్డ్ మార్చండి', 'Sign Out': 'సైన్ అవుట్',
    'Good morning': 'శుభోదయం', 'Good afternoon': 'శుభ మధ్యాహ్నం', 'Good evening': 'శుభ సాయంత్రం',
    "Here's what's happening with your cases today.": 'ఈరోజు మీ కేసులలో ఇది జరుగుతుంది.',
    'Total Cases': 'మొత్తం కేసులు', 'SLA Breached': 'SLA ఉల్లంఘన',
    'File New Case': 'కొత్త కేసు నమోదు', 'Schedule Hearing': 'విచారణ షెడ్యూల్',
    'Recent Cases': 'ఇటీవలి కేసులు', 'View all →': 'అన్నీ చూడండి →',
    'No cases yet.': 'ఇంకా కేసులు లేవు.', 'File your first case': 'మీ మొదటి కేసు నమోదు చేయండి',
    'No cases available yet.': 'ఇంకా కేసులు అందుబాటులో లేవు.',
    'ID': 'ID', 'TITLE': 'శీర్షిక', 'STATUS': 'స్థితి', 'FILED': 'దాఖలు తేదీ', 'View': 'చూడండి',
    '+ File New Case': '+ కొత్త కేసు', 'Filter by status:': 'స్థితి ద్వారా ఫిల్టర్:',
    'All': 'అన్నీ', 'Refresh': 'రిఫ్రెష్', 'No cases found': 'కేసులు కనుగొనబడలేదు', 'Loading...': 'లోడ్ అవుతోంది...',
    'Title': 'శీర్షిక', 'Litigant': 'వాది', 'Lawyer': 'న్యాయవాది', 'Filed': 'దాఖలు', 'Open': 'తెరవండి',
    'Case Title': 'కేసు శీర్షిక', 'Litigant ID (user email or id)': 'వాది ID',
    'Lawyer ID (optional)': 'న్యాయవాది ID (ఐచ్ఛికం)', 'Filing...': 'నమోదు అవుతోంది...', 'File Case': 'కేసు నమోదు',
    '+ Schedule Hearing': '+ విచారణ', 'Filter:': 'ఫిల్టర్:', 'No hearings': 'విచారణలు లేవు',
    'Case': 'కేసు', 'Judge': 'న్యాయమూర్తి', 'Date': 'తేదీ', 'Time': 'సమయం',
    'Case ID': 'కేసు ID', 'Judge ID': 'న్యాయమూర్తి ID', 'Hearing Date': 'విచారణ తేదీ',
    'Hearing Time': 'విచారణ సమయం', 'Schedule Slot ID': 'స్లాట్ ID',
    'Scheduled By (user id)': 'షెడ్యూల్ చేసినవారు (వినియోగదారు ID)', 'Scheduling...': 'షెడ్యూల్ అవుతోంది...',
    'Generate Report': 'రిపోర్ట్ రూపొందించు', 'Generating...': 'రూపొందిస్తోంది...',
    'Back': 'వెనక్కి', 'Save': 'సేవ్', 'Cancel': 'రద్దు', 'Submit': 'సమర్పించు',
    'Name': 'పేరు', 'Email': 'ఇమెయిల్', 'Role': 'పాత్ర', 'Action': 'చర్య',
    'Welcome back': 'తిరిగి స్వాగతం', 'Sign in to your CaseFlow account': 'మీ CaseFlow ఖాతాలో సైన్ ఇన్ చేయండి',
    'Email address': 'ఇమెయిల్ చిరునామా', 'Password': 'పాస్‌వర్డ్', 'Remember me': 'నన్ను గుర్తుంచుకో',
    'Forgot password?': 'పాస్‌వర్డ్ మర్చిపోయారా?', 'Sign In': 'సైన్ ఇన్',
    "Don't have an account?": 'ఖాతా లేదా?', 'Create one': 'సృష్టించండి',
    '← Back to home': '← హోమ్‌కు వెళ్ళు', 'Already have an account?': 'ఈసారికే ఖాతా ఉందా?', 'Sign in': 'సైన్ ఇన్',
    'Register as a Litigant on CaseFlow': 'CaseFlow లో వాదిగా నమోదు చేసుకోండి',
    'Full Name': 'పూర్తి పేరు', 'Phone (10 digits)': 'ఫోన్ (10 అంకెలు)',
    'Password (min 6 characters)': 'పాస్‌వర్డ్ (కనీసం 6 అక్షరాలు)',
    'Create a secure password': 'సురక్షిత పాస్‌వర్డ్ సృష్టించండి', 'Creating...': 'సృష్టిస్తోంది...',
    'Create Account': 'ఖాతా సృష్టించు', 'No appeals found': 'అపీల్స్ కనుగొనబడలేదు',
  },

  marathi: {
    'Overview': 'आढावा', 'Case Management': 'प्रकरण व्यवस्थापन', 'Hearings': 'सुनावण्या',
    'Legal Process': 'कायदेशीर प्रक्रिया', 'Admin & Reports': 'अॅडमिन आणि अहवाल',
    'Dashboard': 'डॅशबोर्ड', 'Cases': 'प्रकरणे', 'File Case': 'प्रकरण दाखल करा',
    'Pending Docs': 'प्रलंबित कागदपत्रे', 'Schedule': 'वेळापत्रक', 'Judge Slots': 'न्यायाधीश स्लॉट्स',
    'Appeals': 'अपील', 'File Appeal': 'अपील दाखल करा', 'Workflow / SLA': 'वर्कफ्लो / SLA',
    'Run Compliance Check': 'अनुपालन तपासणी चालवा', 'Compliance Records': 'अनुपालन नोंदी',
    'Audits': 'ऑडिट', 'Reports': 'अहवाल', 'Users': 'वापरकर्ते',
    'Audit Logs': 'ऑडिट लॉग्स', 'Notifications': 'सूचना', 'Navigation': 'नेव्हिगेशन',
    'More': 'अधिक', 'Settings': 'सेटिंग्ज', 'Theme': 'थीम', 'Language': 'भाषा',
    'Dark': 'डार्क', 'Light': 'लाइट', 'Change Password': 'पासवर्ड बदला', 'Sign Out': 'साइन आउट',
    'Good morning': 'सुप्रभात', 'Good afternoon': 'शुभ दुपार', 'Good evening': 'शुभ संध्याकाळ',
    "Here's what's happening with your cases today.": 'आज तुमच्या प्रकरणांमध्ये हे घडत आहे.',
    'Total Cases': 'एकूण प्रकरणे', 'SLA Breached': 'SLA उल्लंघन',
    'File New Case': 'नवीन प्रकरण दाखल करा', 'Schedule Hearing': 'सुनावणी निश्चित करा',
    'Recent Cases': 'अलीकडील प्रकरणे', 'View all →': 'सर्व पहा →',
    'No cases yet.': 'अद्याप कोणतेही प्रकरण नाही.', 'File your first case': 'तुमचे पहिले प्रकरण दाखल करा',
    'No cases available yet.': 'अद्याप कोणतेही प्रकरण उपलब्ध नाही.',
    'ID': 'ID', 'TITLE': 'शीर्षक', 'STATUS': 'स्थिती', 'FILED': 'दाखल तारीख', 'View': 'पहा',
    '+ File New Case': '+ नवीन प्रकरण', 'Filter by status:': 'स्थितीनुसार फिल्टर:',
    'All': 'सर्व', 'Refresh': 'रिफ्रेश', 'No cases found': 'कोणतेही प्रकरण सापडले नाही', 'Loading...': 'लोड होत आहे...',
    'Title': 'शीर्षक', 'Litigant': 'वादी', 'Lawyer': 'वकील', 'Filed': 'दाखल', 'Open': 'उघडा',
    'Case Title': 'प्रकरणाचे शीर्षक', 'Litigant ID (user email or id)': 'वादी ID',
    'Lawyer ID (optional)': 'वकील ID (पर्यायी)', 'Filing...': 'दाखल होत आहे...', 'File Case': 'प्रकरण दाखल करा',
    '+ Schedule Hearing': '+ सुनावणी', 'Filter:': 'फिल्टर:', 'No hearings': 'कोणतीही सुनावणी नाही',
    'Case': 'प्रकरण', 'Judge': 'न्यायाधीश', 'Date': 'तारीख', 'Time': 'वेळ',
    'Case ID': 'प्रकरण ID', 'Judge ID': 'न्यायाधीश ID', 'Hearing Date': 'सुनावणीची तारीख',
    'Hearing Time': 'सुनावणीची वेळ', 'Schedule Slot ID': 'स्लॉट ID',
    'Scheduled By (user id)': 'निश्चित केलेले (वापरकर्ता ID)', 'Scheduling...': 'निश्चित होत आहे...',
    'Generate Report': 'अहवाल तयार करा', 'Generating...': 'तयार होत आहे...',
    'Back': 'मागे', 'Save': 'जतन करा', 'Cancel': 'रद्द करा', 'Submit': 'सबमिट करा',
    'Name': 'नाव', 'Email': 'ईमेल', 'Role': 'भूमिका', 'Action': 'क्रिया',
    'Welcome back': 'पुन्हा स्वागत आहे', 'Sign in to your CaseFlow account': 'तुमच्या CaseFlow खात्यात साइन इन करा',
    'Email address': 'ईमेल पत्ता', 'Password': 'पासवर्ड', 'Remember me': 'मला लक्षात ठेवा',
    'Forgot password?': 'पासवर्ड विसरलात?', 'Sign In': 'साइन इन',
    "Don't have an account?": 'खाते नाही?', 'Create one': 'तयार करा',
    '← Back to home': '← होमवर परत', 'Already have an account?': 'आधीच खाते आहे?', 'Sign in': 'साइन इन',
    'Register as a Litigant on CaseFlow': 'CaseFlow वर वादी म्हणून नोंदणी करा',
    'Full Name': 'पूर्ण नाव', 'Phone (10 digits)': 'फोन (10 अंक)',
    'Password (min 6 characters)': 'पासवर्ड (किमान 6 अक्षरे)',
    'Create a secure password': 'सुरक्षित पासवर्ड तयार करा', 'Creating...': 'तयार होत आहे...',
    'Create Account': 'खाते तयार करा', 'No appeals found': 'कोणतेही अपील सापडले नाही',
  },

  kannada: {
    'Overview': 'ಒವರ್‌ವ್ಯೂ', 'Case Management': 'ಕೇಸ್ ನಿರ್ವಹಣೆ', 'Hearings': 'ವಿಚಾರಣೆಗಳು',
    'Legal Process': 'ಕಾನೂನು ಪ್ರಕ್ರಿಯೆ', 'Admin & Reports': 'ಆಡ್ಮಿನ್ ಮತ್ತು ವರದಿಗಳು',
    'Dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್', 'Cases': 'ಕೇಸ್‌ಗಳು', 'File Case': 'ಕೇಸ್ ದಾಖಲಿಸಿ',
    'Pending Docs': 'ಬಾಕಿ ದಾಖಲೆಗಳು', 'Schedule': 'ಷೆಡ್ಯೂಲ್', 'Judge Slots': 'ನ್ಯಾಯಾಧೀಶ ಸ್ಲಾಟ್‌ಗಳು',
    'Appeals': 'ಅಪೀಲುಗಳು', 'File Appeal': 'ಅಪೀಲ್ ದಾಖಲಿಸಿ', 'Workflow / SLA': 'ವರ್ಕ್‌ಫ್ಲೋ / SLA',
    'Run Compliance Check': 'ಅನುಪಾಲನಾ ಪರಿಶೀಲನೆ ನಡೆಸಿ', 'Compliance Records': 'ಅನುಪಾಲನಾ ದಾಖಲೆಗಳು',
    'Audits': 'ಆಡಿಟ್‌ಗಳು', 'Reports': 'ವರದಿಗಳು', 'Users': 'ಬಳಕೆದಾರರು',
    'Audit Logs': 'ಆಡಿಟ್ ಲಾಗ್‌ಗಳು', 'Notifications': 'ಅಧಿಸೂಚನೆಗಳು', 'Navigation': 'ನವಿಗೇಶನ್',
    'More': 'ಇನ್ನಷ್ಟು', 'Settings': 'ಸೆಟ್ಟಿಂಗ್ಸ್', 'Theme': 'ಥೀಮ್', 'Language': 'ಭಾಷೆ',
    'Dark': 'ಡಾರ್ಕ್', 'Light': 'ಲೈಟ್', 'Change Password': 'ಪಾಸ್‌ವರ್ಡ್ ಬದಲಿಸಿ', 'Sign Out': 'ಸೈನ್ ಔಟ್',
    'Good morning': 'ಶುಭೋದಯ', 'Good afternoon': 'ಶುಭ ಮಧ್ಯಾಹ್ನ', 'Good evening': 'ಶುಭ ಸಂಜೆ',
    "Here's what's happening with your cases today.": 'ಇಂದು ನಿಮ್ಮ ಕೇಸ್‌ಗಳಲ್ಲಿ ಇದು ನಡೆಯುತ್ತಿದೆ.',
    'Total Cases': 'ಒಟ್ಟು ಕೇಸ್‌ಗಳು', 'SLA Breached': 'SLA ಉಲ್ಲಂಘನೆ',
    'File New Case': 'ಹೊಸ ಕೇಸ್ ದಾಖಲಿಸಿ', 'Schedule Hearing': 'ವಿಚಾರಣೆ ನಿಗದಿಪಡಿಸಿ',
    'Recent Cases': 'ಇತ್ತೀಚಿನ ಕೇಸ್‌ಗಳು', 'View all →': 'ಎಲ್ಲ ನೋಡಿ →',
    'No cases yet.': 'ಇನ್ನೂ ಕೇಸ್‌ಗಳಿಲ್ಲ.', 'File your first case': 'ನಿಮ್ಮ ಮೊದಲ ಕೇಸ್ ದಾಖಲಿಸಿ',
    'No cases available yet.': 'ಇನ್ನೂ ಕೇಸ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ.',
    'ID': 'ID', 'TITLE': 'ಶೀರ್ಷಿಕೆ', 'STATUS': 'ಸ್ಥಿತಿ', 'FILED': 'ದಾಖಲು ದಿನಾಂಕ', 'View': 'ನೋಡಿ',
    '+ File New Case': '+ ಹೊಸ ಕೇಸ್', 'Filter by status:': 'ಸ್ಥಿತಿಯ ಮೂಲಕ ಫಿಲ್ಟರ್:',
    'All': 'ಎಲ್ಲ', 'Refresh': 'ರಿಫ್ರೆಶ್', 'No cases found': 'ಕೇಸ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ', 'Loading...': 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'Title': 'ಶೀರ್ಷಿಕೆ', 'Litigant': 'ವಾದಿ', 'Lawyer': 'ವಕೀಲ', 'Filed': 'ದಾಖಲು', 'Open': 'ತೆರೆ',
    'Case Title': 'ಕೇಸ್ ಶೀರ್ಷಿಕೆ', 'Litigant ID (user email or id)': 'ವಾದಿ ID',
    'Lawyer ID (optional)': 'ವಕೀಲ ID (ಐಚ್ಛಿಕ)', 'Filing...': 'ದಾಖಲಿಸುತ್ತಿದೆ...', 'File Case': 'ಕೇಸ್ ದಾಖಲಿಸಿ',
    '+ Schedule Hearing': '+ ವಿಚಾರಣೆ', 'Filter:': 'ಫಿಲ್ಟರ್:', 'No hearings': 'ವಿಚಾರಣೆಗಳಿಲ್ಲ',
    'Case': 'ಕೇಸ್', 'Judge': 'ನ್ಯಾಯಾಧೀಶ', 'Date': 'ದಿನಾಂಕ', 'Time': 'ಸಮಯ',
    'Case ID': 'ಕೇಸ್ ID', 'Judge ID': 'ನ್ಯಾಯಾಧೀಶ ID', 'Hearing Date': 'ವಿಚಾರಣಾ ದಿನಾಂಕ',
    'Hearing Time': 'ವಿಚಾರಣಾ ಸಮಯ', 'Schedule Slot ID': 'ಸ್ಲಾಟ್ ID',
    'Scheduled By (user id)': 'ನಿಗದಿಪಡಿಸಿದವರು (ಬಳಕೆದಾರ ID)', 'Scheduling...': 'ನಿಗದಿ ಮಾಡಲಾಗುತ್ತಿದೆ...',
    'Generate Report': 'ವರದಿ ರಚಿಸಿ', 'Generating...': 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    'Back': 'ಹಿಂದೆ', 'Save': 'ಸೇವ್', 'Cancel': 'ರದ್ದು', 'Submit': 'ಸಲ್ಲಿಸಿ',
    'Name': 'ಹೆಸರು', 'Email': 'ಇಮೇಲ್', 'Role': 'ಪಾತ್ರ', 'Action': 'ಕ್ರಿಯೆ',
    'Welcome back': 'ಮತ್ತೆ ಸ್ವಾಗತ', 'Sign in to your CaseFlow account': 'ನಿಮ್ಮ CaseFlow ಖಾತೆಗೆ ಸೈನ್ ಇನ್ ಮಾಡಿ',
    'Email address': 'ಇಮೇಲ್ ವಿಳಾಸ', 'Password': 'ಪಾಸ್‌ವರ್ಡ್', 'Remember me': 'ನನ್ನನ್ನು ನೆನಪಿಡಿ',
    'Forgot password?': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿದ್ದೀರಾ?', 'Sign In': 'ಸೈನ್ ಇನ್',
    "Don't have an account?": 'ಖಾತೆ ಇಲ್ಲವೇ?', 'Create one': 'ರಚಿಸಿ',
    '← Back to home': '← ಮುಖಪುಟಕ್ಕೆ ಹಿಂದಿರುಗಿ', 'Already have an account?': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?', 'Sign in': 'ಸೈನ್ ಇನ್',
    'Register as a Litigant on CaseFlow': 'CaseFlow ನಲ್ಲಿ ವಾದಿಯಾಗಿ ನೋಂದಾಯಿಸಿ',
    'Full Name': 'ಪೂರ್ಣ ಹೆಸರು', 'Phone (10 digits)': 'ಫೋನ್ (10 ಅಂಕಿಗಳು)',
    'Password (min 6 characters)': 'ಪಾಸ್‌ವರ್ಡ್ (ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳು)',
    'Create a secure password': 'ಸುರಕ್ಷಿತ ಪಾಸ್‌ವರ್ಡ್ ರಚಿಸಿ', 'Creating...': 'ರಚಿಸಲಾಗುತ್ತಿದೆ...',
    'Create Account': 'ಖಾತೆ ರಚಿಸಿ', 'No appeals found': 'ಅಪೀಲುಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem('caseflow-language') || 'english')

  useEffect(() => {
    localStorage.setItem('caseflow-language', language)
  }, [language])

  const t = (text) => translations[language]?.[text] || translations.english?.[text] || text

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider')
  return ctx
}

