server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/soham-dutta-cog/caseflow_config_server.git
          default-label: rashad-config
          clone-on-start: true
          skip-ssl-validation: true
          username: rashadahmedz
          password: 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

          my-new-repo:
            pattern: "iam-service"
            uri: https://github.com/soham-dutta-cog/caseflow_config_server.git
            username: varun-2S
            password: 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
            default-label: varun-branch
            clone-on-start: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true