server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/varun-2s/caseflow_config_server.git
          default-label: main
          clone-on-start: true
          skip-ssl-validation: true
          username: varun-2s
          password: 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

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true