server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/soham-dutta-cog/caseflow_config_server.git
          default-label: main
          clone-on-start: true
          skip-ssl-validation: true
          username: soham-dutta-cog
          password: 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

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true