server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/soham-dutta-cog/caseflow_config_server.git
          default-label: kalai-config
          clone-on-start: true
          skip-ssl-validation: true
          username: kalaikumarp-png
          password: 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

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true